### PR TITLE
update fs2 to 1.0.0-M1

### PR DESCRIPTION
**Pull request by wedens**
Most changes are `s/Effect/ConcurrentEffect/g`.  Also `ExecutionContext` is now required only when resolving `ConcurrentEffect` which makes `notificationPool` useless.

### CODE REVIEW

**Comment by timperrett** [comment]
@adelbertc how does this affect us with nelson? @rossabaker for visibility

**Comment by wedens** [comment]
And please tell me if I've missed some place where  specific `ExecutionContext` was important (blocking or something).

**Comment by wedens** [comment]
`Concurrent` is required for things like `Stream#joinUnbounded` and some functions need `Effect` (e.g. I've seen `runAsync` somewhere). `ConcurrentEffect` is just those two combined.

**Comment by wedens** [comment]
Also, I suspect `Resource#load` should be shifting to some blocking `ExecutionContext`.

**Comment by wedens** [comment]
Looks like it's already updated in master. Closing.

**Pull request closed without merging**
