### PR TITLE
fs2-core-1.0.0-M5

### PR DESCRIPTION
**Pull request by dbousamra**
I've upgraded FS2 to 1.0.0-M5. This in turn upgrades cats-effect to 1.0.0.

### CODE REVIEW

**Comment by dbousamra** [comment]
Not needed now.

**Comment by tpolecat** [comment]
Can we update this to 1.0.0 and merge and publish? I'm blocked on this.

**Comment by tpolecat** [comment]
Thanks @rossabaker 👍

**Comment by rossabaker** [comment]
I think @wedens is correct on #61 about `Resource#load` and replacing the watcher, but this is no worse than what we had before.

How about we release this as 7.0.0-M1 to unblock, and we can clean up the rest as 7.0.0?  Otherwise, it'll be two major version bumps.

**Comment by rossabaker** [comment]
Merging this now.  Discussion of release ongoing in Nelson gitter.

**Pull request merged**
