### PR TITLE
Interpolate environment variables in imports

### LINKED ISSUE #53: String substitution not working
I'm trying to import files using string substitution but it seems it is not working as in the documentation

If I for example do this

```
web-server {
    import "$(user.home)/test.cfg"
}
```

I get an exception saying 
```
java.io.FileNotFoundException: /home/software/seqexec_server_gs_test-0.2.0/conf/$(user.home)/test.cfg (No such file or directory)
```

The same happens if I use `$(HOME)`

Should this work?

### PR DESCRIPTION
**Pull request by rossabaker**
Fixes #53

### CODE REVIEW

**Comment by rossabaker** [comment]
A couple discussion points before we clear this for release:

- Changed types of public `importsOf` and `resolveImports`.  I'm not sure that these really should be public in the first place.  This is, as it stands, a breaking change.
- Should we be able to interpolate mutable names into imports, like config values and system properties?  Or should import interpolation be limited to immutable values, like `sys.env`?  I reused the binding interpolator here, but it might be considered too permissive when we start to think about things like file watching.

**Comment by timperrett** [comment]
@rossabaker im not wild on a major version breaking change for this functionality. Is there a way it can be done in a bin-compat manner? Perhaps we could (should?) just document the cases that dont work (not a huge fan of this, but i don't want to have to upgrade all the users right now)

**Comment by rossabaker** [comment]
This should pass MiMa (I'll add that later to be sure).  It deprecates methods that neither worked nor are likely to be used.

Supports only environment variables in import directives.  This is all the documentation ever promised (now made more explicit), and sidesteps all issues of how we monitor mutable bindings.

**Comment by timperrett** [comment]
@rossabaker im happy with this :-) thanks!

**Pull request merged**
